App: #应用信息
  Name: jimoos-public
  Author:
  Description: 积墨开源公开库
  Addons:
    - Name: jm-ping
      Ref: jimoos-public
      Group: base
      SourceType: git
      Source:
      Description: 用于测试服务器是否可 ping
      Type: module
      DependOns: none
      Conflicts: none
      Migrations: migrations
      Docs: docs
